id: A355A46BC
title: Prayer on the Occasion of the Reading Transmission for the Omniscient King
  of Dharma's Thirteen-Volume Collected Writings
type: translation
pechas:
- I7D44C36B
- I7A7AA3C6
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:02:44.774072
  last_modified_at: 2023-01-04 12:02:44.774093
  collections:
  - Jamyang Gyaltsen Series
  - Works of Tibetan Masters
alignment_to_base:
  I7D44C36B/77AA: F776
  I7A7AA3C6/81F3: F776
